FORMAT: 1A
HOST: https://www.atlas-se.hu/api

# Bátmonostori Atlas SE Cikkek

Az Atlas SE Cikkek egy olyan API, amivel az Atlas SE sportegyesület cikkeit lehetséges lekérni JSON formátumban.

## Cikkek [/articles]

### Minden Cikk megjelenítése [GET]

+ Response 200 (application/json)

        [
            {
                "articles":[
                    {
                        "title": "Asd"
                        "Author": "Zick Balázs"
                        "Body": "ASd"
                        "Date": "Now"
                    }
                ]
            }
        ]